import {Engine} from './engine.mjs';
const $=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d');
let W=innerWidth,H=innerHeight,dpr=1,game=null,paused=false,finished=false,keys=new Set(),joy={x:0,y:0},dodge=false,seed=1,isDaily=false,shownMode='',clock=0,last=0,audio=null,sound=false;
const STORE='reedlight-v1';let save={wins:0,runs:0,best:0,bestKills:0,evolutions:[],daily:{}};let storageOkay=true;
try{const v=JSON.parse(localStorage.getItem(STORE));if(v&&typeof v==='object'){for(const k of ['wins','runs','best','bestKills'])if(Number.isFinite(v[k])&&v[k]>=0)save[k]=Math.min(v[k],1e7);if(Array.isArray(v.evolutions))save.evolutions=v.evolutions.filter(x=>typeof x==='string').slice(0,20);if(v.daily&&typeof v.daily==='object')save.daily=v.daily;}}catch{storageOkay=false;}
function persist(){try{localStorage.setItem(STORE,JSON.stringify(save));storageOkay=true;}catch{storageOkay=false;}}
function record(){ $('record').textContent=`${save.wins} 次迎來晨光　·　最長 ${Math.floor(save.best)} 秒　·　${save.evolutions.length} 種進化${storageOkay?'':' · 無法讀寫儲存，仍可遊玩'}`;}record();
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);}addEventListener('resize',resize);resize();
function tone(freq=500,duration=.08){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.start();o.stop(audio.currentTime+duration);}catch{}}
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=`音效 ${sound?'開':'關'}`;tone();};
function modal(eyebrow,title,desc,body,actions){$('modalEyebrow').textContent=eyebrow;$('modalTitle').textContent=title;$('modalDesc').textContent=desc;$('modalBody').replaceChildren(...body);$('modalActions').replaceChildren(...actions);$('modal').hidden=false;}
function button(text,fn,primary=false){const b=document.createElement('button');b.textContent=text;b.onclick=fn;if(primary)b.className='primary';return b;}
function start(daily=false){isDaily=daily;seed=daily?Number(new Date().toISOString().slice(0,10).replaceAll('-','')):crypto.getRandomValues(new Uint32Array(1))[0];game=new Engine(seed);paused=false;finished=false;shownMode='';keys.clear();joy={x:0,y:0};$('home').hidden=true;$('hud').hidden=false;$('pause').hidden=false;$('modal').hidden=true;document.body.classList.add('playing');tone(700,.2);}
$('start').onclick=()=>start();$('daily').onclick=()=>start(true);
function home(){game=null;paused=false;keys.clear();$('modal').hidden=true;$('home').hidden=false;$('hud').hidden=true;$('pause').hidden=true;document.body.classList.remove('playing');record();}
function pause(){if(!game||game.state.mode!=='play')return;paused=true;keys.clear();joy={x:0,y:0};modal('TAKE A BREATH','停在這片光裡','世界已暫停。回來時，再一起往前走。',[],[button('繼續守夜',()=>{paused=false;$('modal').hidden=true;},true),button('結束本局',()=>{save.runs++;persist();home();})]);}
$('pause').onclick=pause;
function guide(){const el=document.createElement('div');el.className='guidecontent';el.innerHTML='<strong>01 / 活下來，讓光種長大</strong><br>WASD 或方向鍵移動，自動攻擊最近的敵人。拾起金色光種累積經驗，每次升級選一項能力。空白鍵翻滾可短暫避開傷害。<br><br><strong>02 / 找到你的武器搭配</strong><br>種子、提燈與漣漪能組成不同流派。升級卡會告訴你進化條件，達成時自動進化。敵人的紅色光圈代表危險。<br><br><strong>03 / 驅散霧冠巨靈</strong><br>2:30 巨靈現身，擊敗牠即勝利；3:30 天光耗盡則失敗。注意血量，翻滾後要等待冷卻。切換分頁會自動暫停。<br><br>每日模式使用 UTC 日期種子；相同操作會產生相同結果。戰績儲存在本機，不含跨裝置同步。';modal('FIELD NOTES','守夜人的野外手冊','', [el],[button('知道了',()=>{$('modal').hidden=true;},true)]);}$('guide').onclick=guide;
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());if(e.repeat)return;if(e.key===' ')dodge=true;if(e.key.toLowerCase()==='p'||e.key==='Escape'){if(paused){paused=false;$('modal').hidden=true;}else pause();}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{keys.clear();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
$('dodge').onpointerdown=e=>{e.preventDefault();dodge=true;};let joyId=null;const stick=$('joystick');function moveJoy(e){if(e.pointerId!==joyId)return;const r=stick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,l=Math.hypot(dx,dy),v=Math.min(1,l/36);joy={x:l?dx/l*v:0,y:l?dy/l*v:0};stick.firstElementChild.style.transform=`translate(${joy.x*30}px,${joy.y*30}px)`;}stick.onpointerdown=e=>{joyId=e.pointerId;stick.setPointerCapture(e.pointerId);moveJoy(e);};stick.onpointermove=moveJoy;function releaseJoy(){joyId=null;joy={x:0,y:0};stick.firstElementChild.style.transform='';}stick.onpointerup=releaseJoy;stick.onpointercancel=releaseJoy;
function upgrade(){const s=game.state;const cards=s.choices.map(c=>{const b=button('',()=>{game.chooseUpgrade(c.id);$('modal').hidden=true;shownMode='';tone(870,.13);});b.className='card';const i=document.createElement('span');i.className='icon';i.textContent=c.icon||'✦';const t=document.createElement('b');t.textContent=c.name+' · '+c.level+' 級';const d=document.createElement('p');d.textContent=c.desc;const small=document.createElement('small');small.textContent='SELECT UPGRADE ↗';b.append(i,t,d,small);return b;});modal('A LITTLE STRONGER',`光種甦醒 · LV.${s.level}`,'選擇一份森林的禮物。時間已暫停。',cards,[]);tone(1000,.15);}
function end(){if(finished)return;finished=true;const s=game.state,win=s.mode==='won';save.runs++;save.wins+=win?1:0;save.best=Math.max(save.best,s.t);save.bestKills=Math.max(save.bestKills,s.kills);save.evolutions=[...new Set([...save.evolutions,...s.evolutions])].slice(0,20);if(isDaily)save.daily={date:new Date().toISOString().slice(0,10),won:win,kills:s.kills};persist();modal(win?'THE FOREST REMEMBERS':'EVERY NIGHT TEACHES',win?'晨光，為你而來。':'先休息，再出發。',`${win?'你驅散了巨靈，替森林留住了光。':'小提燈熄了，但你的勇氣還在。'} ${Math.floor(s.t)} 秒 · ${s.kills} 驅散 · LV.${s.level}${isDaily?' · 每日種子 '+seed:''}`,[],[button('再守一夜',()=>start(isDaily),true),button('回到營地',home)]);tone(win?1000:220,.4);}
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}function path(points,color){ctx.fillStyle=color;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fill();}
function tree(x,y,size=1){ctx.save();ctx.translate(x,y);ctx.scale(size,size);ellipse(8,9,40,13,'#081f205c');ctx.fillStyle='#496047';ctx.fillRect(-6,-47,12,49);path([[-47,-28],[0,-109],[45,-28]],'#254e3e');path([[-40,-50],[0,-126],[33,-50]],'#315c44');path([[-31,-77],[0,-142],[26,-77]],'#426e4d');path([[0,-142],[26,-77],[7,-81]],'#254f3c');ctx.restore();}
function duck(x,y,size=1,time=0,facing=1){ctx.save();ctx.translate(x,y);ctx.scale(size,size);const bob=Math.sin(time*5)*2;ellipse(0,10,25,8,'#001a1b55');ctx.translate(0,bob);ellipse(-8,6,9,4,'#edb267');ellipse(10,6,9,4,'#edb267');ellipse(0,-11,21,22,'#dedec0');ellipse(-4,-14,17,21,'#f2edce');path([[-19,-18],[-29,-27],[-20,-4]],'#e2e6c3');ellipse(4,-37,18,18,'#f6f0ce');ellipse(16*facing,-34,13,6,'#f4b85f');ellipse(10*facing,-41,2.6,3.3,'#233e32');ellipse(11*facing,-42,1,1,'#fff');path([[-15,-29],[18,-27],[14,-21],[-14,-22]],'#ce7757');path([[-13,-23],[-24,-13],[-22,-29]],'#ac6048');ellipse(-3,-54,17,5,'#385e45');path([[-13,-55],[-8,-64],[9,-62],[15,-53]],'#4d7850');ctx.strokeStyle='#b6c89d';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(17,-19);ctx.lineTo(32,-17);ctx.stroke();ellipse(33,-1,12,5,'#edc55a1f');ctx.shadowColor='#ffcb65';ctx.shadowBlur=25;ctx.fillStyle='#edbe57';ctx.fillRect(26,-17,13,17);ctx.shadowBlur=0;ctx.strokeStyle='#536242';ctx.strokeRect(26,-17,13,17);ctx.fillStyle='#ffe9a1';ctx.fillRect(30,-13,5,10);ctx.restore();}
const scenery=Array.from({length:190},(_,i)=>{const n=Math.sin(i*127.1+45.3)*43758.5453,m=Math.sin(i*311.7+97)*31758.545;return{x:(n-Math.floor(n))*1800,y:(m-Math.floor(m))*1800,s:.65+(i%7)/10,type:i%4};});
function enemy(e){const x=e.x,y=e.y,r=e.r;ellipse(x+2,y+4,r*1.1,r*.4,'#00141550');const boss=e.isBoss;if(e.charge>0){ctx.strokeStyle='#ed977d';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,r+8,0,7);ctx.stroke();}const col=e.hitFlash>0?'#fff0c4':boss?'#b8926a':e.kind==='wasp'?'#d18f70':e.kind==='beetle'?'#9eacd0':'#779580';ellipse(x,y-r*.5,r,r*.95,col);ellipse(x-r*.27,y-r*.7,r*.13,r*.16,'#142a2a');ellipse(x+r*.3,y-r*.7,r*.13,r*.16,'#142a2a');if(boss){path([[x-r,y-r],[x-r*.8,y-r*1.9],[x-r*.2,y-r*1.4],[x+r*.25,y-r*2],[x+r*.6,y-r*1.3],[x+r,y-r*1.7],[x+r,y-r]],'#d4bb77');ctx.strokeStyle='#ffcf7980';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,r+8,0,7);ctx.stroke();}else{path([[x-r*.8,y-r],[x-r*1.2,y-r*1.7],[x-r*.25,y-r*1.25]],col);path([[x+r*.8,y-r],[x+r*1.2,y-r*1.7],[x+r*.25,y-r*1.25]],col);}if(e.hp<e.maxHp){ctx.fillStyle='#112a25';ctx.fillRect(x-r,y-r*2.2,r*2,3);ctx.fillStyle='#dcac81';ctx.fillRect(x-r,y-r*2.2,r*2*e.hp/e.maxHp,3);}}
function render(time){ctx.clearRect(0,0,W,H);const s=game?.state,scale=s?Math.max(.65,Math.min(1.15,W/950,H/620)):Math.min(1.2,W/1100);const camX=s?s.p.x:870,camY=s?s.p.y:870;ctx.fillStyle='#183c32';ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(s?W/2:W*.75,s?H/2:H*.65);ctx.scale(scale,scale);ctx.translate(-camX,-camY);
ctx.fillStyle='#294b37';ctx.fillRect(0,0,1800,1800);ctx.strokeStyle='#5e775624';ctx.lineWidth=120;ctx.beginPath();ctx.moveTo(80,1630);ctx.bezierCurveTo(1300,1350,310,440,1750,80);ctx.stroke();for(const o of scenery){if(Math.abs(o.x-camX)>W/scale||Math.abs(o.y-camY)>H/scale)continue;if(o.type===0){ellipse(o.x,o.y,15,7,'#4a695449');ctx.strokeStyle='#75975b66';ctx.lineWidth=2;for(let i=0;i<4;i++){ctx.beginPath();ctx.moveTo(o.x+i*4,o.y);ctx.lineTo(o.x+i*5-5,o.y-14-i*2);ctx.stroke();}}else if(o.type===1){ellipse(o.x,o.y,18,10,'#4e6854');ellipse(o.x-3,o.y-4,13,6,'#61765b');}}
if(s){for(let i=0;i<s.orbitCount;i++){const a=s.orbitAngle+i*Math.PI*2/s.orbitCount;ctx.shadowBlur=18;ctx.shadowColor='#e7ef92';ellipse(s.p.x+Math.cos(a)*s.orbitRadius,s.p.y+Math.sin(a)*s.orbitRadius,6,6,'#eaf7b4');ctx.shadowBlur=0;}for(const g of s.gems){ctx.shadowColor='#ead477';ctx.shadowBlur=8;path([[g.x,g.y-5],[g.x+4,g.y],[g.x,g.y+5],[g.x-4,g.y]],'#f2d682');}ctx.shadowBlur=0;for(const b of s.bullets){ellipse(b.x,b.y,b.r,b.r,b.owner==='enemy'?'#df8a72':b.kind==='seed'?'#ffe3a0':'#afd8ac');}for(const f of s.effects){ctx.globalAlpha=Math.min(1,f.life/(f.maxLife||1));if(f.kind==='wave'){ctx.strokeStyle='#d9ebae';ctx.lineWidth=4;ctx.beginPath();ctx.arc(f.x,f.y,Math.max(1,f.r*(1-f.life/(f.maxLife||1))),0,7);ctx.stroke();}if(f.kind==='text'||f.text){ctx.fillStyle='#ffe9a5';ctx.font='bold 16px system-ui';ctx.fillText(f.text||'',f.x,f.y);}else{ctx.strokeStyle=f.kind==='danger'?'#ec987f':'#d3eeb8';ctx.lineWidth=3;ctx.beginPath();ctx.arc(f.x,f.y,Math.max(1,f.r),0,7);ctx.stroke();}}ctx.globalAlpha=1;}
const things=scenery.filter(o=>o.type>1&&Math.abs(o.x-camX)<W/scale&&Math.abs(o.y-camY)<H/scale).map(o=>({y:o.y,draw:()=>{ctx.globalAlpha=s&&Math.abs(o.x-s.p.x)<75&&o.y>s.p.y-10&&o.y<s.p.y+175?.28:1;tree(o.x,o.y,o.s);ctx.globalAlpha=1;}}));if(s){things.push(...s.enemies.map(e=>({y:e.y,draw:()=>enemy(e)})));things.push({y:s.p.y,draw:()=>{ctx.globalAlpha=s.p.invuln>0?.65:1;duck(s.p.x,s.p.y,1.15,time,s.p.facingX<0?-1:1);ctx.globalAlpha=1;}});}else things.push({y:920,draw:()=>duck(890,920,3.5,time)});things.sort((a,b)=>a.y-b.y).forEach(o=>o.draw());ctx.restore();
const gradient=ctx.createRadialGradient(W*.65,H*.5,40,W*.6,H*.5,W*.8);gradient.addColorStop(0,'#d5dc8900');gradient.addColorStop(1,s?'#001a1933':'#071f19c9');ctx.fillStyle=gradient;ctx.fillRect(0,0,W,H);if(!s){const g=ctx.createLinearGradient(0,0,W,0);g.addColorStop(0,'#102d27f5');g.addColorStop(.48,'#102d27bb');g.addColorStop(.78,'#102d2700');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);}for(let i=0;i<22;i++){const x=((i*193.71+time*5)%W),y=((i*79.3+Math.sin(time+i)*16)%H);ellipse(x,y,1.5,1.5,`rgba(236,226,141,${.2+Math.sin(time+i)*.17})`);}}
function hud(){const s=game.state;$('hptext').textContent=`${Math.ceil(s.p.hp)} / ${s.p.maxHp}`;$('hpbar').style.width=`${Math.max(0,s.p.hp/s.p.maxHp)*100}%`;$('xpbar').style.width=`${Math.min(100,s.xp/s.nextXp*100)}%`;$('time').textContent=`${String(Math.floor(s.t/60)).padStart(2,'0')}:${String(Math.floor(s.t%60)).padStart(2,'0')}`;$('phase').textContent=s.t>=150?'巨靈現身 · 驅散牠':s.t>90?'深夜 · 霧潮湧動':s.t>45?'林間 · 危機靠近':'薄霧 · 光種萌芽';$('level').textContent=`LV.${s.level}`;$('kills').textContent=`${s.kills} 驅散`;$('boss').hidden=!s.bossSpawned||s.bossHp<=0;$('bossbar').style.width=`${s.bossHp/s.bossMaxHp*100}%`;$('dodge').innerHTML=s.p.dodgeCooldown>0?`${s.p.dodgeCooldown.toFixed(1)}<br><small>冷卻中</small>`:'翻滾<br><small>SPACE</small>';$('loadout').textContent=s.evolutions.length?'✦ '+s.evolutions.map(x=>({sunflower:'向日葵齊射',halo:'日輪提燈',tide:'破曉潮音'})[x]||x).join(' · '):`光種收集 ${s.xp} / ${s.nextXp}`;$('tip').textContent=s.t<12?'拾起光種升級；升級時世界會暫停。':s.t<24?'空白鍵 / 右下翻滾：危急時穿過敵群。':isDaily?`每日種子 ${seed}`:'2:30 巨靈現身 · 擊敗巨靈迎接晨光';}
function frame(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;clock+=dt;if(game&&!paused){const x=joy.x+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),y=joy.y+(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);game.update(dt,{x,y,dodge});dodge=false;if(game.state.mode!==shownMode){shownMode=game.state.mode;if(shownMode==='upgrade')upgrade();if(['won','lost'].includes(shownMode))end();}}render(clock);if(game)hud();requestAnimationFrame(frame);}requestAnimationFrame(frame);
