import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import { Engine } from './engine.mjs';
// DOM/Canvas boundary harness, not a substitute for a real browser visual test.
function harness(stored='null',writeFails=false){
  const nodes=new Map(),events={},docEvents={};
  const context=new Proxy({}, {get:(t,k)=>t[k]??(k==='createRadialGradient'||k==='createLinearGradient'?()=>({addColorStop(){}}):()=>{}),set:(t,k,v)=>(t[k]=v,true)});
  function node(){return {hidden:false,style:{},classList:{add(){},remove(){}},children:[],textContent:'',innerHTML:'',append(...x){this.children.push(...x)},replaceChildren(...x){this.children=x},getContext:()=>context,getBoundingClientRect:()=>({left:0,top:0,width:100,height:100}),setPointerCapture(){},firstElementChild:{style:{}}};}
  const localStorage={getItem:()=>stored,setItem:(k,v)=>{if(writeFails)throw Error('disabled');stored=v;}};
  const sandbox={Engine,console,Math,Date,JSON,Number,Set,Uint32Array,innerWidth:1280,innerHeight:800,devicePixelRatio:1,crypto:{getRandomValues:a=>(a[0]=123,a)},localStorage,requestAnimationFrame:f=>sandbox.frame=f,addEventListener:(k,f)=>events[k]=f,document:{hidden:false,body:node(),getElementById:id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id)},createElement:()=>node(),addEventListener:(k,f)=>docEvents[k]=f}};
  sandbox.window=sandbox;vm.createContext(sandbox);let code=fs.readFileSync(new URL('./app.mjs',import.meta.url),'utf8').replace("import {Engine} from './engine.mjs';",'');code+='\n;globalThis.inspect=()=>({game,paused,save,storageOkay,seed,shownMode});';vm.runInContext(code,sandbox);return {sandbox,nodes,events,docEvents,stored:()=>stored};
}
test('home, field guide, legal start, drawing, pause and restart wire correctly',()=>{const h=harness(),n=h.nodes,s=h.sandbox;assert.ok(n.get('record').textContent.includes('0 次'));n.get('guide').onclick();assert.equal(n.get('modalTitle').textContent,'守夜人的野外手冊');n.get('modalActions').children[0].onclick();assert.equal(n.get('modal').hidden,true);n.get('start').onclick();const a=s.inspect().game;h.events.keydown({key:'d',preventDefault(){}});for(let i=0;i<120;i++)s.frame(i*16.67);assert.ok(a.state.p.x>900);assert.ok(n.get('hptext').textContent.includes('/'));h.events.blur();assert.equal(s.inspect().paused,true);const t=a.state.t;s.frame(5000);assert.equal(a.state.t,t);n.get('modalActions').children[0].onclick();assert.equal(s.inspect().paused,false);h.sandbox.document.hidden=true;h.docEvents.visibilitychange();assert.equal(s.inspect().paused,true);n.get('modalActions').children[1].onclick();assert.equal(s.inspect().game,null);assert.equal(n.get('home').hidden,false);n.get('start').onclick();assert.equal(s.inspect().game.state.t,0);assert.notEqual(s.inspect().game,a);});
test('corrupt and unavailable storage do not prevent runs',()=>{for(const [value,fail] of [['{broken',false],['null',true],['{"wins":-99,"evolutions":[5,null,"halo"]}',false]]){const h=harness(value,fail);h.nodes.get('start').onclick();assert.equal(h.sandbox.inspect().game.state.p.hp,100);h.nodes.get('pause').onclick();h.nodes.get('modalActions').children[1].onclick();assert.equal(h.sandbox.inspect().game,null);}});
test('daily seed is stable and virtual joystick resets on cancellation',()=>{const h=harness();h.nodes.get('daily').onclick();const seed=h.sandbox.inspect().seed;h.nodes.get('pause').onclick();h.nodes.get('modalActions').children[1].onclick();h.nodes.get('daily').onclick();assert.equal(h.sandbox.inspect().seed,seed);const j=h.nodes.get('joystick');j.onpointerdown({pointerId:1,clientX:90,clientY:50});for(let i=0;i<60;i++)h.sandbox.frame(i*16.67);const p=h.sandbox.inspect().game.state.p;assert.ok(p.x>900);j.onpointercancel();const x=p.x;for(let i=60;i<90;i++)h.sandbox.frame(i*16.67);assert.equal(p.x,x);});
